# Generated by Django 5.1.4 on 2025-01-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
